# Generated by Django 4.2.13 on 2026-06-14 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(default='Expenses_Export.csv', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('paid_by', models.CharField(max_length=100)),
                ('paid_to', models.CharField(blank=True, max_length=100)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_settlements', to='importer.importsession')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('paid_by', models.CharField(max_length=100)),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_original', models.CharField(default='INR', max_length=10)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('split_type', models.CharField(max_length=20)),
                ('split_with', models.JSONField(default=list)),
                ('split_details', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_refund', models.BooleanField(default=False)),
                ('has_anomaly', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_expenses', to='importer.importsession')),
            ],
            options={
                'ordering': ['date', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=10)),
                ('raw_description', models.CharField(blank=True, max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_records', to='importer.importsession')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
